[package]
name = 'faerr'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'faerr'

[dependencies]
# extendr-api = '*'
faer = '*'
rayon = '*'
extendr-api = { git = "https://github.com/extendr/extendr", features = [
    "faer",
] }
