# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_faerr_wrappers", use_symbols = TRUE, package_name = "faerr")

#' @usage NULL
#' @useDynLib faerr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

foo <- function(some_mat) .Call(wrap__foo, some_mat)


# nolint end
